// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38-i5cIhc7Z9CvZQ8pTE82wx18futRsI',
    appId: '1:989234656465:web:971c6f66d460a7f16b81f0',
    messagingSenderId: '989234656465',
    projectId: 'webwhatsappsystem',
    authDomain: 'webwhatsappsystem.firebaseapp.com',
    storageBucket: 'webwhatsappsystem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRcyh40kajoeQdBhEhKhbjvb5-GAMJEM',
    appId: '1:989234656465:android:8b9650584c21f4776b81f0',
    messagingSenderId: '989234656465',
    projectId: 'webwhatsappsystem',
    storageBucket: 'webwhatsappsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe711QPKDSZwocNjIf9TtuLF2MXoKvgCE',
    appId: '1:989234656465:ios:2b70cc6c1e4703026b81f0',
    messagingSenderId: '989234656465',
    projectId: 'webwhatsappsystem',
    storageBucket: 'webwhatsappsystem.appspot.com',
    iosClientId: '989234656465-7eq9g6kd6euoslancq6jfcau48kt4m62.apps.googleusercontent.com',
    iosBundleId: 'br.com.dcbsystem.webwhatsappsystem',
  );
}
